In [1]:
# import numpy
import numpy as np

import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

**Task:** create matrix (2x2) matrix 'A'


In [3]:
A = np.array([[4,3],[-3,5]])

**Task:**

In [ ]:
"""
Define function 'shape_2x2' which checks if matrix has shape (2x2)

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""

In [18]:
def shape(x):
    if x.shape == (2,2):
        return True
    return False


**Task:**

In [ ]:
"""
Define function 'determinant_2x2' which computes determinant of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

Do not forget to check the shape of  the input matrix.
"""


In [20]:
def determinant(x):
    if shape(x):
        return np.linalg.det(x)
    

In [13]:
determinant(A)

28.99999999999999

**Task:** call the function 'determinant_2x2' with matrix 'A' 

**Task:** compute the eigenvectors, eigenvalues of matrix 'A' with numpy

In [14]:
eigenvals, V = np.linalg.eig(A)

**Task:** print eigenvalues

In [15]:
eigenvals

array([4.5+2.95803989j, 4.5-2.95803989j])

**Task:** print eigenvectors

In [16]:
V

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.11785113+0.69721669j, 0.11785113-0.69721669j]])

**Task:**

In [ ]:
"""
Define function 'eig_2x2' which computes eigenvectors and eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

Do not use np.linalg.eig function!
Use 'shape_2x2' and 'determinant_2x2' functions. 
Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of 2x2 matrix:
https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/
"""

In [28]:
def eig(x):
    if shape(x):
        return np.roots([1,-(np.trace(x)), np.linalg.det(x)])
        
    

In [29]:
eig(A)

array([4.5+2.95803989j, 4.5-2.95803989j])

**Task:** call the function 'deig_2x2' with matrix 'A' 

In [30]:
def evec_from_eval(A, eval_A):
    n = A.shape[0]
    evec_A = np.zeros((n, n))
    for k in range(n):
        M = np.delete(A, k, axis=0)
        M = np.delete(M, k, axis=1)
        eval_M = np.linalg.eigvals(M)

        nominator = [np.prod(eval_A[i] - eval_M) for i in range(n)]
        denominator = [np.prod(np.delete(eval_A[i] - eval_A, i)) for i in range(n)]

        evec_A[k, :] = np.array(nominator) / np.array(denominator)
    return evec_A


**Task:** compare the result with numpy function (to comparison use np.allclose function)

**Task:** define matrix B = np.array([[0,1],[-1,0]]) 

**Task:** compute eigenvalues and eigevectors of matrix 'B' with numpy and with 'eig_2x2' function

**Task:** compare the results with numpy function (to comparison use np.allclose function)

**Task:** print eigenvalues and eigenvectors and try to explain why the solutions is different